[package]
name = "remoppt"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
enigo = "0.3.0"
local-ip-address = "0.6.5"
qr2term = "0.3.3"
tokio = { version = "1.45.0", features = ["full"] }
